baseurl: ""
permalink: pretty
title: 'Tereza Bártová'

logo:
  mobile: "images/logo/tb-logo-blur.jpg"
  mobile_height: "64px"
  mobile_width: "64px"
  desktop: "images/logo/tb-logo-blur.jpg"
  desktop_height: "128px"
  desktop_width: "128px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  media:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "media"
    values:
      layout: "media"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
